package sh.leaflab.goods.datagen;

import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.ModelProvider;
import net.minecraft.data.PackOutput;

import sh.leaflab.goods.TheGoods;

// A BlockItem with no explicit item model here is auto-generated by ModelProvider to reference its block model.
public class ModModelProvider extends ModelProvider {
    public ModModelProvider(PackOutput output) {
        super(output, TheGoods.MODID);
    }

    @Override
    protected void registerModels(BlockModelGenerators blockModels, ItemModelGenerators itemModels) {
        blockModels.createTrivialCube(TheGoods.TRADE_HUB.get());
        blockModels.createTrivialCube(TheGoods.DEPOSITOR.get());
    }
}
