package sh.leaflab.goods.datagen;

import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.ModelProvider;
import net.minecraft.client.data.models.MultiVariant;
import net.minecraft.client.data.models.blockstates.MultiVariantGenerator;
import net.minecraft.client.data.models.blockstates.PropertyDispatch;
import net.minecraft.client.data.models.model.ModelLocationUtils;
import net.minecraft.client.data.models.model.TexturedModel;
import net.minecraft.client.renderer.block.dispatch.Variant;
import net.minecraft.core.Direction;
import net.minecraft.data.PackOutput;
import net.minecraft.util.random.WeightedList;
import net.minecraft.world.level.block.HorizontalDirectionalBlock;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;

import sh.leaflab.goods.TheGoods;

// A BlockItem with no explicit item model here is auto-generated by ModelProvider to reference its block model.
//
// The Trade Hub's model bakes literal per-face UV crops out of a single texture (a Blockbench cube UV-unwrap),
// which BlockModelGenerators' parent+texture templates can't express — so the model itself is a static asset
// under src/main/resources rather than generated here. Only the FACING blockstate rotation is generated.
//
// The Depositor uses vanilla's furnace-style orientable-cube template instead (TexturedModel.ORIENTABLE_ONLY_TOP:
// separate top/side/front textures, front rotated to face FACING) since its shape is a plain cube with a distinct
// front face. Its FACING is BlockStateProperties.FACING_HOPPER (down + 4 horizontal, never up, matching vanilla's
// Hopper), so the rotation dispatch is built by hand rather than via createHorizontallyRotatedBlock, which only
// covers the 4 horizontal directions.
public class ModModelProvider extends ModelProvider {
    public ModModelProvider(PackOutput output) {
        super(output, TheGoods.MODID);
    }

    @Override
    protected void registerModels(BlockModelGenerators blockModels, ItemModelGenerators itemModels) {
        MultiVariant depositorModel = BlockModelGenerators.plainVariant(
                TexturedModel.ORIENTABLE_ONLY_TOP.create(TheGoods.DEPOSITOR.get(), blockModels.modelOutput));
        blockModels.blockStateOutput.accept(
                MultiVariantGenerator.dispatch(TheGoods.DEPOSITOR.get(), depositorModel)
                        .with(PropertyDispatch.modify(BlockStateProperties.FACING_HOPPER)
                                .select(Direction.DOWN, BlockModelGenerators.X_ROT_90)
                                .select(Direction.NORTH, BlockModelGenerators.NOP)
                                .select(Direction.SOUTH, BlockModelGenerators.Y_ROT_180)
                                .select(Direction.WEST, BlockModelGenerators.Y_ROT_270)
                                .select(Direction.EAST, BlockModelGenerators.Y_ROT_90)));

        MultiVariant model = new MultiVariant(WeightedList.of(new Variant(ModelLocationUtils.getModelLocation(TheGoods.TRADE_HUB.get()))));
        blockModels.blockStateOutput.accept(
                MultiVariantGenerator.dispatch(TheGoods.TRADE_HUB.get(), model)
                        .with(PropertyDispatch.modify(HorizontalDirectionalBlock.FACING)
                                .select(Direction.NORTH, BlockModelGenerators.NOP)
                                .select(Direction.EAST, BlockModelGenerators.Y_ROT_90)
                                .select(Direction.SOUTH, BlockModelGenerators.Y_ROT_180)
                                .select(Direction.WEST, BlockModelGenerators.Y_ROT_270)));
    }
}
