name: Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup build environment
        uses: ./.github/actions/setup-build-env

      - name: Build & Unit Test
        run: ./gradlew build

      - name: Run Integration Tests
        run: ./gradlew runGameTestServer
