name: Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup build environment
        uses: ./.github/actions/setup-build-env

      - name: Build & Unit Test
        run: ./gradlew build

      - name: Run Integration Tests
        run: ./gradlew runGameTestServer
